global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'haproxy'
    static_configs:
      - targets: ['localhost:9101']
